# Generated by Django 6.1.1 on 2026-09-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=60)),
                ('direccion', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
